# fly.toml app configuration file generated for manga-manager on 2023-06-05T08:33:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "manga-manager"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
